window.PaperPulseDashboard = (() => {
  const api = window.PaperPulseApi; const ui = window.PaperPulseUi; const utils = window.PaperPulseUtils; const storageKey = 'paperpulse-dashboard-v2'; let records = []; let query = ''; let releasedVisibleRows = window.PaperPulseConfig.releasedInitialRows;
  function readCache() { try { const cached = JSON.parse(sessionStorage.getItem(storageKey)); return cached && Date.now() - cached.savedAt < window.PaperPulseConfig.dashboardCacheMs ? cached : null; } catch { return null; } }
  function saveCache(data) { try { sessionStorage.setItem(storageKey, JSON.stringify({ ...data, savedAt: Date.now() })); } catch { /* Storage is optional. */ } }
  function newest(first, second) { return utils.timestamp(second.lastUpdated) - utils.timestamp(first.lastUpdated); }
  function render() { const matched = records.filter((record) => utils.matchesDocument(record, query)); const released = matched.filter((record) => record.status === 'Released').sort(newest); const progress = matched.filter((record) => record.status !== 'Released').sort(newest); const allReleased = records.filter((record) => record.status === 'Released'); const allProgress = records.filter((record) => record.status !== 'Released'); ui.renderTable('released', released, allReleased.length, releasedVisibleRows); ui.renderTable('progress', progress, allProgress.length, 30); document.getElementById('dashboardStatus').textContent = query ? `Dashboard filtered by "${utils.normalizeQuery(query)}".` : ''; }
  async function load(force = false) { const refreshButton = document.getElementById('refreshButton'); const cached = !force && readCache(); if (cached) { records = cached.records; ui.renderStats(cached.stats, cached.updatedAt); render(); return; } refreshButton.disabled = true; ui.showDashboardLoading(); try { const [listResponse, statsResponse] = await Promise.all([api.list(window.PaperPulseConfig.dashboardRecordLimit), api.stats()]); records = listResponse.data || []; const data = { records, stats: statsResponse.data, updatedAt: statsResponse.updatedAt }; saveCache(data); ui.renderStats(data.stats, data.updatedAt); render(); } catch (error) { ui.showDashboardError(error.message); ['released', 'progress'].forEach((kind) => { document.getElementById(`${kind}TableLoading`).hidden = true; document.getElementById(`${kind}Empty`).hidden = false; }); } finally { refreshButton.disabled = false; } }
  function find(tracking) { return records.find((record) => record.trackingNumber === tracking); }
  function openFromRow(row) { const record = find(row.dataset.tracking); if (record) ui.openModal(record, row); }
  function init() { document.getElementById('refreshButton').addEventListener('click', () => { sessionStorage.removeItem(storageKey); releasedVisibleRows = window.PaperPulseConfig.releasedInitialRows; load(true); }); document.getElementById('viewMoreReleased').addEventListener('click', () => { releasedVisibleRows += window.PaperPulseConfig.releasedLoadMoreRows; render(); }); document.querySelector('.dashboard-section').addEventListener('click', (event) => { const row = event.target.closest('tbody tr'); if (row) openFromRow(row); }); document.querySelector('.dashboard-section').addEventListener('keydown', (event) => { const row = event.target.closest('tbody tr'); if (row && (event.key === 'Enter' || event.key === ' ')) { event.preventDefault(); openFromRow(row); } }); document.getElementById('closeModal').addEventListener('click', ui.closeModal); document.getElementById('detailModal').addEventListener('click', (event) => { if (event.target.closest('[data-close-modal]')) ui.closeModal(); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && !document.getElementById('detailModal').hidden) ui.closeModal(); }); const scrollTop = document.getElementById('scrollTop'); window.addEventListener('scroll', () => { scrollTop.hidden = window.scrollY < 500; }, { passive: true }); scrollTop.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' })); }
  return { init, load, filter: (value) => { query = value; releasedVisibleRows = window.PaperPulseConfig.releasedInitialRows; render(); } };
})();
