window.PaperPulseUi = (() => {
  const $ = (id) => document.getElementById(id); const utils = window.PaperPulseUtils;
  const states = ['loadingState', 'emptyState', 'notFoundState', 'errorState', 'resultCard'];
  function showState(id) { states.forEach((state) => { $(state).hidden = state !== id; }); }
  function setLoading(isLoading) { $('searchButton').disabled = isLoading; $('searchButton').querySelector('span').textContent = isLoading ? 'Searching...' : 'Search'; if (isLoading) showState('loadingState'); }
  function fillDetails(prefix, document) { $(`${prefix}Tracking`).textContent = document.trackingNumber || '-'; $(`${prefix}Office`).textContent = document.requestingOffice || '-'; $(`${prefix}Received`).textContent = utils.formatDate(document.dateReceived); $(`${prefix}Signed`).textContent = utils.formatDate(document.dateSigned); $(`${prefix}Updated`).textContent = utils.formatDateTime(document.lastUpdated); $(`${prefix}Remarks`).textContent = document.remarks || 'No remarks recorded.'; }
  function renderResult(document) { $('documentSubject').textContent = document.subject || 'Untitled document'; $('trackingNumber').textContent = document.trackingNumber || '-'; $('office').textContent = document.requestingOffice || '-'; $('receivedDate').textContent = utils.formatDate(document.dateReceived); $('signedDate').textContent = utils.formatDate(document.dateSigned); $('lastUpdated').textContent = utils.formatDateTime(document.lastUpdated); $('remarks').textContent = document.remarks || 'No remarks recorded.'; setBadge($('statusBadge'), document.status); showState('resultCard'); }
  function setBadge(element, status) { element.textContent = status || 'Received'; element.className = `status-badge status-badge--${utils.statusClass(status)}`; }
  function renderStats(stats, updatedAt) { const ids = { Received: 'receivedCount', 'For Signature': 'signatureCount', Signed: 'signedCount', Released: 'releasedCount' }; Object.entries(ids).forEach(([status, id]) => { $(id).textContent = Number(stats?.[status] || 0).toLocaleString('en-PH'); }); $('summaryCards').setAttribute('aria-busy', 'false'); if (updatedAt) $('statsUpdated').textContent = `Last synchronized ${utils.formatDateTime(updatedAt)}`; }
  function renderSuggestions(items, activeIndex = -1) { const list = $('suggestions'); list.replaceChildren(); if (!items.length) { list.hidden = true; $('searchInput').setAttribute('aria-expanded', 'false'); return; } items.forEach((item, index) => { const option = document.createElement('li'); option.id = `suggestion-${index}`; option.role = 'option'; option.dataset.query = item.trackingNumber; option.className = index === activeIndex ? 'is-active' : ''; option.innerHTML = `<strong>${utils.escapeHtml(item.trackingNumber)}</strong><span>${utils.escapeHtml(item.subject)}</span>`; list.append(option); }); list.hidden = false; $('searchInput').setAttribute('aria-expanded', 'true'); }
  function clearSuggestions() { renderSuggestions([]); }
  function showError(message) { $('errorMessage').textContent = message; showState('errorState'); }
  function tableRow(record, columns) { const row = document.createElement('tr'); row.tabIndex = 0; row.dataset.tracking = record.trackingNumber; row.setAttribute('role', 'button'); row.setAttribute('aria-label', `View details for ${record.trackingNumber}`); const cells = columns.map((column) => { const value = column === 'status' ? '' : column === 'dateSigned' ? utils.formatDate(record[column]) : column === 'lastUpdated' ? utils.formatDateTime(record[column]) : record[column] || '-'; return `<td>${utils.escapeHtml(value)}</td>`; }); if (columns.includes('status')) cells[columns.indexOf('status')] = `<td><span class="status-badge status-badge--${utils.statusClass(record.status)}">${utils.escapeHtml(record.status || 'Received')}</span></td>`; row.innerHTML = `${cells.join('')}<td><span class="table-action" aria-hidden="true"><i class="fa-solid fa-chevron-right"></i></span></td>`; return row; }
  function renderTable(kind, records, total, visibleLimit) { const isReleased = kind === 'released'; const body = $(`${kind}TableBody`); const wrap = $(`${kind}TableWrap`); const empty = $(`${kind}Empty`); const loading = $(`${kind}TableLoading`); const counter = $(`${kind}Counter`); const limit = isReleased ? visibleLimit : 30; const visible = records.slice(0, limit); body.replaceChildren(); visible.forEach((record) => body.append(tableRow(record, isReleased ? ['trackingNumber', 'subject', 'requestingOffice', 'dateSigned', 'lastUpdated'] : ['trackingNumber', 'subject', 'requestingOffice', 'status', 'lastUpdated']))); loading.hidden = true; empty.hidden = records.length > 0; wrap.hidden = records.length === 0; counter.textContent = records.length ? `Showing ${visible.length} of ${total}` : total ? `0 of ${total}` : 'No documents'; if (isReleased) $('viewMoreReleased').hidden = visible.length >= records.length; }
  function showDashboardLoading() { ['released', 'progress'].forEach((kind) => { $(`${kind}TableLoading`).hidden = false; $(`${kind}TableWrap`).hidden = true; $(`${kind}Empty`).hidden = true; }); }
  function showDashboardError(message) { $('dashboardStatus').textContent = message; }
  let lastFocus;
  function openModal(document, opener) { lastFocus = opener || document.activeElement; $('modalTitle').textContent = document.subject || 'Untitled document'; fillDetails('modal', document); setBadge($('modalStatus'), document.status); $('detailModal').hidden = false; document.body.classList.add('modal-open'); $('closeModal').focus(); }
  function closeModal() { $('detailModal').hidden = true; document.body.classList.remove('modal-open'); if (lastFocus?.focus) lastFocus.focus(); }
  return { showState, setLoading, renderResult, renderStats, renderSuggestions, clearSuggestions, showError, renderTable, showDashboardLoading, showDashboardError, openModal, closeModal };
})();
