window.PaperPulseUi = (() => {
  const $ = (id) => document.getElementById(id); const utils = window.PaperPulseUtils;
  const states = ['loadingState', 'emptyState', 'notFoundState', 'errorState', 'resultCard'];
  function showState(id) { states.forEach((state) => { $(state).hidden = state !== id; }); }
  function setLoading(isLoading) { $('searchButton').disabled = isLoading; $('searchButton').querySelector('span').textContent = isLoading ? 'Searching…' : 'Search'; if (isLoading) showState('loadingState'); }
  function renderResult(document) { $('documentSubject').textContent = document.subject || 'Untitled document'; $('trackingNumber').textContent = document.trackingNumber || '—'; $('office').textContent = document.requestingOffice || '—'; $('receivedDate').textContent = utils.formatDate(document.dateReceived); $('signedDate').textContent = utils.formatDate(document.dateSigned); $('lastUpdated').textContent = utils.formatDate(document.lastUpdated); $('remarks').textContent = document.remarks || 'No remarks recorded.'; const badge = $('statusBadge'); badge.textContent = document.status || 'Received'; badge.className = `status-badge status-badge--${utils.statusClass(document.status)}`; showState('resultCard'); }
  function renderStats(stats, updatedAt) { const ids = { Received: 'receivedCount', 'For Signature': 'signatureCount', Signed: 'signedCount', Released: 'releasedCount' }; Object.entries(ids).forEach(([status, id]) => { $(id).textContent = Number(stats?.[status] || 0).toLocaleString('en-PH'); }); $('summaryCards').setAttribute('aria-busy', 'false'); $('statsUpdated').textContent = updatedAt ? `Checked ${utils.formatDate(updatedAt)}` : ''; }
  function renderSuggestions(items, activeIndex = -1) { const list = $('suggestions'); list.replaceChildren(); if (!items.length) { list.hidden = true; $('searchInput').setAttribute('aria-expanded', 'false'); return; } items.forEach((item, index) => { const option = document.createElement('li'); option.id = `suggestion-${index}`; option.role = 'option'; option.dataset.query = item.trackingNumber; option.className = index === activeIndex ? 'is-active' : ''; option.innerHTML = `<strong>${utils.escapeHtml(item.trackingNumber)}</strong><span>${utils.escapeHtml(item.subject)}</span>`; list.append(option); }); list.hidden = false; $('searchInput').setAttribute('aria-expanded', 'true'); }
  function clearSuggestions() { renderSuggestions([]); }
  function showError(message) { $('errorMessage').textContent = message; showState('errorState'); }
  return { showState, setLoading, renderResult, renderStats, renderSuggestions, clearSuggestions, showError };
})();
